### ISSUE TITLE
How to hide file path?

### ISSUE THREAD

**Issue by ryadaj** [mottox2/obsidian-relation-pane#1]
Hello! 

Thanks for this wonderful plugin. I'm just wondering: how do I hide the file path? 

<img width="686" alt="Screenshot 2022-12-02 at 21 01 38" src="https://user-images.githubusercontent.com/82765301/205417254-271b9838-3c83-4c39-af69-9ca25752cd74.png">

**Comment by mottox2** [comment]
Thanks for the great feedback. I will think about the feature.

**Comment by OttoVanluchene** [comment]
I was just looking for a setting that does just that :)

**Comment by mottox2** [comment]
I added settings screen and create an option to not display folder names **as a experimental feature.**

<img width="1430" alt="CleanShot 2023-01-08 at 16 42 05@2x" src="https://user-images.githubusercontent.com/7007253/211185669-dca0f5e4-0af4-4d8a-8212-fd02a68aabe0.png">
